version: "3.6"
services:

  cron:
    image: kennyhyun/alpine-cron
    build:
      context: ./build
    volumes:
      - ./cron/crontabs:/etc/cron.d
      - ./cron/scripts:/scripts
    environment:
      - TZ=${TZ:-Australia/Sydney}
    networks:
      - default
